/*
 * Copyright (C) 2015 Giuseppe Cardone <ippatsuman@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package net.gcardone.junidecode;

/**
 * Character map for Unicode characters with codepoint U+1Dxx.
 * @author Giuseppe Cardone
 * @version 0.1
 */
class X1d {

    public static final String[] map = new String[]{
        "a", // 0x00
        "[?]", // 0x01
        "[?]", // 0x02
        "b", // 0x03
        "c", // 0x04
        "d", // 0x05
        "d", // 0x06
        "e", // 0x07
        "[?]", // 0x08
        "[?]", // 0x09
        "j", // 0x0a
        "k", // 0x0b
        "l", // 0x0c
        "m", // 0x0d
        "n", // 0x0e
        "o", // 0x0f
        "c", // 0x10
        "o", // 0x11
        "c", // 0x12
        "0", // 0x13
        "[?]", // 0x14
        "[?]", // 0x15
        "n", // 0x16
        "u", // 0x17
        "p", // 0x18
        "r", // 0x19
        "r", // 0x1a
        "t", // 0x1b
        "u", // 0x1c
        "[?]", // 0x1d
        "[?]", // 0x1e
        "[?]", // 0x1f
        "v", // 0x20
        "w", // 0x21
        "z", // 0x22
        "3", // 0x23
        "s", // 0x24
        "[?]", // 0x25
        "[?]", // 0x26
        "a", // 0x27
        "[?]", // 0x28
        "p", // 0x29
        "[?]", // 0x2a
        "[?]", // 0x2b
        "a", // 0x2c
        "[?]", // 0x2d
        "b", // 0x2e
        "b", // 0x2f
        "d", // 0x30
        "e", // 0x31
        "[?]", // 0x32
        "g", // 0x33
        "h", // 0x34
        "i", // 0x35
        "j", // 0x36
        "k", // 0x37
        "l", // 0x38
        "m", // 0x39
        "n", // 0x3a
        "n", // 0x3b
        "o", // 0x3c
        "o", // 0x3d
        "p", // 0x3e
        "r", // 0x3f
        "t", // 0x40
        "u", // 0x41
        "w", // 0x42
        "a", // 0x43
        "a", // 0x44
        "a", // 0x45
        "[?]", // 0x46
        "b", // 0x47
        "d", // 0x48
        "e", // 0x49
        "e", // 0x4a
        "3", // 0x4b
        "[?]", // 0x4c
        "g", // 0x4d
        "i", // 0x4e
        "k", // 0x4f
        "m", // 0x50
        "n", // 0x51
        "o", // 0x52
        "c", // 0x53
        "n", // 0x54
        "u", // 0x55
        "p", // 0x56
        "t", // 0x57
        "u", // 0x58
        "u", // 0x59
        "m", // 0x5a
        "v", // 0x5b
        "[?]", // 0x5c
        "b", // 0x5d
        "[?]", // 0x5e
        "[?]", // 0x5f
        "[?]", // 0x60
        "x", // 0x61
        "i", // 0x62
        "r", // 0x63
        "u", // 0x64
        "v", // 0x65
        "b", // 0x66
        "y", // 0x67
        "e", // 0x68
        "[?]", // 0x69
        "x", // 0x6a
        "[?]", // 0x6b
        "b", // 0x6c
        "d", // 0x6d
        "f", // 0x6e
        "m", // 0x6f
        "n", // 0x70
        "p", // 0x71
        "r", // 0x72
        "f", // 0x73
        "s", // 0x74
        "t", // 0x75
        "z", // 0x76
        "g", // 0x77
        "h", // 0x78
        "[?]", // 0x79
        "th", // 0x7a
        "i", // 0x7b
        "t", // 0x7c
        "p", // 0x7d
        "u", // 0x7e
        "u", // 0x7f
        "[?]", // 0x80
        "[?]", // 0x81
        "[?]", // 0x82
        "[?]", // 0x83
        "[?]", // 0x84
        "[?]", // 0x85
        "[?]", // 0x86
        "[?]", // 0x87
        "[?]", // 0x88
        "[?]", // 0x89
        "[?]", // 0x8a
        "[?]", // 0x8b
        "[?]", // 0x8c
        "[?]", // 0x8d
        "[?]", // 0x8e
        "[?]", // 0x8f
        "[?]", // 0x90
        "[?]", // 0x91
        "[?]", // 0x92
        "[?]", // 0x93
        "[?]", // 0x94
        "[?]", // 0x95
        "[?]", // 0x96
        "[?]", // 0x97
        "[?]", // 0x98
        "[?]", // 0x99
        "[?]", // 0x9a
        "[?]", // 0x9b
        "[?]", // 0x9c
        "[?]", // 0x9d
        "[?]", // 0x9e
        "[?]", // 0x9f
        "[?]", // 0xa0
        "[?]", // 0xa1
        "[?]", // 0xa2
        "[?]", // 0xa3
        "[?]", // 0xa4
        "[?]", // 0xa5
        "[?]", // 0xa6
        "[?]", // 0xa7
        "[?]", // 0xa8
        "[?]", // 0xa9
        "[?]", // 0xaa
        "[?]", // 0xab
        "[?]", // 0xac
        "[?]", // 0xad
        "[?]", // 0xae
        "[?]", // 0xaf
        "[?]", // 0xb0
        "[?]", // 0xb1
        "[?]", // 0xb2
        "[?]", // 0xb3
        "[?]", // 0xb4
        "[?]", // 0xb5
        "[?]", // 0xb6
        "[?]", // 0xb7
        "[?]", // 0xb8
        "[?]", // 0xb9
        "[?]", // 0xba
        "[?]", // 0xbb
        "[?]", // 0xbc
        "[?]", // 0xbd
        "[?]", // 0xbe
        "[?]", // 0xbf
        "[?]", // 0xc0
        "[?]", // 0xc1
        "[?]", // 0xc2
        "[?]", // 0xc3
        "[?]", // 0xc4
        "[?]", // 0xc5
        "[?]", // 0xc6
        "[?]", // 0xc7
        "[?]", // 0xc8
        "[?]", // 0xc9
        "[?]", // 0xca
        "[?]", // 0xcb
        "[?]", // 0xcc
        "[?]", // 0xcd
        "[?]", // 0xce
        "[?]", // 0xcf
        "[?]", // 0xd0
        "[?]", // 0xd1
        "[?]", // 0xd2
        "[?]", // 0xd3
        "[?]", // 0xd4
        "[?]", // 0xd5
        "[?]", // 0xd6
        "[?]", // 0xd7
        "[?]", // 0xd8
        "[?]", // 0xd9
        "[?]", // 0xda
        "[?]", // 0xdb
        "[?]", // 0xdc
        "[?]", // 0xdd
        "[?]", // 0xde
        "[?]", // 0xdf
        "[?]", // 0xe0
        "[?]", // 0xe1
        "[?]", // 0xe2
        "[?]", // 0xe3
        "[?]", // 0xe4
        "[?]", // 0xe5
        "[?]", // 0xe6
        "[?]", // 0xe7
        "[?]", // 0xe8
        "[?]", // 0xe9
        "[?]", // 0xea
        "[?]", // 0xeb
        "[?]", // 0xec
        "[?]", // 0xed
        "[?]", // 0xee
        "[?]", // 0xef
        "[?]", // 0xf0
        "[?]", // 0xf1
        "[?]", // 0xf2
        "[?]", // 0xf3
        "[?]", // 0xf4
        "[?]", // 0xf5
        "[?]", // 0xf6
        "[?]", // 0xf7
        "[?]", // 0xf8
        "[?]", // 0xf9
        "[?]", // 0xfa
        "[?]", // 0xfb
        "[?]", // 0xfc
        "[?]", // 0xfd
        "[?]", // 0xfe
        "[?]" // 0xff
    };
}