name: Api Scripts CD

on:
  push:
    branches:
      - main
    paths:
      - 'apiscripts/**'
      - '!src/**'
      - '!pom.xml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Upload to server
        if: github.event.repository.fork == false
        run: |
          curl \
          -F 'apiscripts/audica_ahriana=@apiscripts/audica_ahriana.lua' \
          -F 'apiscripts/btd6_gurrenm4=@apiscripts/btd6_gurrenm4.lua' \
          -F 'apiscripts/btd6_inferno=@apiscripts/btd6_inferno.lua' \
          -F 'apiscripts/curseforge=@apiscripts/curseforge.lua' \
          -F 'apiscripts/musedash=@apiscripts/musedash.lua' \
          -F 'apiscripts/thunderstore=@apiscripts/thunderstore.lua' \
          -F 'apiscripts/tld=@apiscripts/tld.lua' \
          -F 'apiscripts/uno=@apiscripts/uno.lua' \
          -F 'apiscripts/vrcmg=@apiscripts/vrcmg.lua' \
          https://${{ secrets.SSH_HOST }}/uploadlum.php?key=${{ secrets.UPLOAD_KEY }}
        shell: bash

      - name: Running remote script
        uses: garygrossgarten/github-action-ssh@release
        if: github.event.repository.fork == false
        with:
          command: |
            python3 ~/downloadApiscripts.py \
            apiscripts/audica_ahriana.lua \
            apiscripts/btd6_gurrenm4.lua \
            apiscripts/btd6_inferno.lua \
            apiscripts/thunderstore.lua \
            apiscripts/curseforge.lua \
            apiscripts/tld.lua \
            apiscripts/uno.lua \
            apiscripts/vrcmg.lua

          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}